version: 2.1

jobs:
  security_scan:
    docker:
      - image: returntocorp/semgrep #semgrep reccomends this docker image
    steps:
      - run:
          name: Scan ts-folder for OWASP top-ten vulnerabilities
          command: semgrep ci --config "p/owasp-top-ten" ts/

workflows:
  version: 2
